### ISSUE TITLE
Connector Lines

### ISSUE THREAD

**Issue by bdlaureano** [emn178/chartjs-plugin-labels#59]
Hello, is there a way to have the values outside with a padding and a line pointing to it's respective slice in the pie?
Example, I have a pie where two slices are very thin, and the values outside are very close, wondering if a line pointing from the slice to the value can be added.

Thank you!

**Comment by Lewke** [comment]
This would be fantastic, only thing stopping us using this plugin at the moment. Otherwise this really fills a gap in chartjs for some orgs.

**Comment by bdlaureano** [comment]
There’s a plug-in that is in the chart ja webpage, called outlabeled, that can do it....!!!
