### ISSUE TITLE
Follow Chart.js plugin rules

### ISSUE THREAD

**Issue by Seb33300** [emn178/chartjs-plugin-labels#66]
Why is your plugin not following [Chart.js plugin conventions](https://www.chartjs.org/docs/latest/developers/plugins.html#configuration)?

Following there conventions makes able to declare plugin options in the related `plugins`
 option provided by Chart.js and your visibility should be increased because we know we can find Chart.js plugins by searching everything starting by `chartjs-plugin-`.

**Comment by emn178** [comment]
long time ago, official document listed some plugins like
https://www.npmjs.com/package/Chart.Annotation.js
https://www.npmjs.com/package/Chart.Zoom.js

so I also follow their naming... 
ok, I will rename project. thank.

**Comment by emn178** [comment]
v1.0.0 rename and change usage.
