### ISSUE TITLE
Bug: Tries to render labels on line-chart

### ISSUE THREAD

**Issue by kosmiq** [emn178/chartjs-plugin-labels#70]
Hi,

So I updated the plugin to version 1.0.0 and changed to the new settings format.

But now I get broken labels on line chart value-points. They should have none at all.

So here's what happens. I have one line chart and one doughnut chart on the same page. With version 0.8.2 I get labels on the doughnut chart as expected and wanted. The line chart is untouched as expected (there is no setting with the object to use the labels plugin).

Upgrading to version 1.0.0 and simply switching to the new syntax keeps the doughnut chart as is and as exptected. However the line chart is affected and gets "NaN%" as inside label. The line chart object has no setting whatsoever that should fire up the piecelabel function on that chart.

If I remove all other charts on the page it still happens. If I clear out my JS-file and keep only the line chart and associated functions I still get the same issue. The only way to make the line chart appear normal again is to roll back to version 0.8.2.

I have not dug any further into this issue other than trying older versions. I'd be happy to try whatever you need.

Running 0.8.2 and the old syntax (everything as expected):
<img width="1193" alt="screen shot 2018-08-24 at 00 17 36" src="https://user-images.githubusercontent.com/322759/44555052-ac425880-a733-11e8-875a-502beeea9e20.png">

Upgrading to 1.0.0 and the new syntax (doughnut as expected, line chart is not):
<img width="1179" alt="screen shot 2018-08-24 at 00 21 55" src="https://user-images.githubusercontent.com/322759/44555076-c3814600-a733-11e8-9a29-1c9b93f80f0e.png">

**Comment by essmd** [comment]
Hi, i also downloaded the latest version to give this plugin a try and i can confirm the issue:
Pie chart looks great and works as expected.

![image](https://user-images.githubusercontent.com/4410142/44571087-12ed6380-a780-11e8-8a3d-7aafaf0c354e.png)

**Comment by emn178** [comment]
this should be fixed in v1.0.1

**Comment by kosmiq** [comment]
Tested 1.0.1 and it does indeed seem to be fixed. Thanks for fast and prompt reply/fix. Closing!

**Comment by benmcm1994** [comment]
This still occurs with chart js v 2.1.0 and chart js labels 1.1.0 on npm. Kosmiq workaround works globally thanks.
